# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- type: show-url
  url: "about:welcome"
  conditions:
      blob-types: [wnp]
      release-types: [release, release-rc, beta]
      products: [comper-browser-pro-lite]
      update-channel: release
      versions: ["<3.0"]
      locales:
          - en-US
          - en-GB